esphome:
  name: lilygot547v23
  friendly_name: LiliyGo T5 4.7 v2.3
  includes:
    - t5_resources/common.h
  libraries:
    - SPI
  platformio_options:
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    platform_packages:
      - "toolchain-riscv32-esp @8.4.0+2021r2-patch5"
    build_flags:
      - "-DBOARD_HAS_PSRAM"
      #- "-DARDUINO_RUNNING_CORE=0"
      #- "-DARDUINO_EVENT_RUNNING_CORE=0"
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
esp32:
  variant: esp32s3
  board: "esp32-s3-devkitc-1"
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.1.1
logger:
api:
  encryption:
    key: !secret api_key
ota:
  platform: esphome
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.112
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  id: wwifi
captive_portal:
web_server:
  port: 80
  include_internal: True
i2c:
  sda: GPIO18
  scl: GPIO17
  scan: false
  id: rtc_bus
  frequency: 100khz
external_components:
  - source:
      type: local
      path: "components/esphome-lilygo-t547plus-main/components"
    components:
      - t547
  - source: "github://kaeltis/esphome-lilygo-t547plus"
    components:
      - lilygo_t5_47_battery
sensor:
  - platform: lilygo_t5_47_battery
    id: battery_voltage
    voltage:
      name: Battery Voltage
  - platform: template
    name: Battery Percentage
    id: battery_percentage
    lambda: |
      // tweak values in mapping for calibration
      // 4.2 = max voltage
      // 3.3 = min voltage
      float y = (id(battery_voltage).voltage->state - 3.3) * 100.0 / (4.2 - 3.3);
      if (y < 100.0)
      { return y; }
      else if (y < 0)
      { return 0.0; }
      else { return 100.0; };
display:
  - platform: t547
    id: my_display
    rotation: 0
    update_interval: 5s
    pages:
      - id: mainPage
        lambda: |
          it.start_clipping(0,0,960,80);
          it.printf(480, 40, id(Roboto_60_Bold), COLOR_ON, TextAlign::CENTER, "Time Example");
          it.end_clipping();
          
          it.start_clipping(0,80,960,130);
          it.printf(480, 105, id(Roboto_40), COLOR_ON, TextAlign::CENTER, "Partial Refresh");
          it.end_clipping();
          if (id(esptime).now().is_valid()) {
            it.start_clipping(0,130,960,230);
            it.printf(480, 180, id(Roboto_90), COLOR_ON, TextAlign::CENTER, "%02d:%02d:%02d", id(esptime).now().hour, id(esptime).now().minute, id(esptime).now().second);
            it.end_clipping();
          
            it.start_clipping(0,230,960,270);
            it.printf(480, 250, id(Roboto_30), COLOR_ON, TextAlign::CENTER, "You should see fast blinking 3 times only digits effectively updated");
            it.end_clipping();
          }
time:
  - platform: homeassistant
    id: esptime          
          
touchscreen:
  - platform: gt911
    interrupt_pin: GPIO47
    id: lily_touch
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
    id: button_left
font:
  - id: Roboto_60_Bold
    file: gfonts://Roboto@700
    size: 60
  - id: Roboto_40
    file: gfonts://Roboto
    size: 40
  - id: Roboto_90
    file: gfonts://Roboto
    size: 90
  - id: Roboto_30
    file: gfonts://Roboto
    size: 30
